### ISSUE TITLE
BUG : front console run time error

### ISSUE THREAD

**Issue by tg201005** [trancendering/Transcendence_Backend#38]
### Issue Type

- [x] Bug (오류)
- [ ] Feature Request (기능 요청)
- [ ] Performance (성능 문제)
- [ ] UI/Design (UI/디자인 관련)
- [ ] Documentation (문서 관련)
- [ ] Enhancement (개선 제안)
- [ ] Other - Please Describe:

### Priority

- [ ] Critical
- [ ] High
- [ ] Medium
- [ ] Low

### Summary

1. 서버에 띄우고 토너먼트 게임을 하던 와중에 에러가 발생함
2. 게임은 정상적으로 실행됨.

### Steps to Reproduce
1. js 파일

<img width="552" alt="스크린샷 2024-02-03 오전 9 38 34" src="https://github.com/trancendering/Transcendence_Backend/assets/84652799/e7d9513d-d909-43e0-a868-8bf522d1fb48">

3. 전체 개요
<img width="527" alt="스크린샷 2024-02-03 오전 9 38 58" src="https://github.com/trancendering/Transcendence_Backend/assets/84652799/a507a3ec-b1a1-4605-b9bb-6ee46f15f230">

4. 구체적인 에러 메시지
<img width="532" alt="스크린샷 2024-02-03 오전 9 39 18" src="https://github.com/trancendering/Transcendence_Backend/assets/84652799/539ccacf-5510-4d4a-93db-efa59b2a1694">

### Environment

- Operating System:
- Browser (if applicable):
- Version:

**Comment by hey-uu** [comment]
저도 이전에 해당 에러가 발생했었는데, chrome extension을 모두 disable한 이후로는 더 이상 그 에러가 나타나지 않았습니다.
chrome extension disable 한 후에도 에러가 계속 발생하는지 확인해주실 수 있을까요?
