### ISSUE TITLE
Bug: Parsing tournament data: TypeError: 에러 발생

### ISSUE THREAD

**Issue by hey-uu** [trancendering/Transcendence_Backend#49]
### Issue Type

- [x] Bug (오류)
- [ ] Feature Request (기능 요청)
- [ ] Performance (성능 문제)
- [ ] UI/Design (UI/디자인 관련)
- [ ] Documentation (문서 관련)
- [ ] Enhancement (개선 제안)
- [ ] Other - Please Describe:

### Priority

- [ ] Critical
- [x] High
- [ ] Medium
- [ ] Low

### Summary

main page와 tournament page를 이동하는 경우 문제가 발생한다.

### Steps to Reproduce

1. main page와 tournament page를 반복해서 이동하다보면 간혹 아래와 같은 문제가 발생한다.
2.
3.
![image](https://github.com/trancendering/Transcendence_Backend/assets/89961266/780bb667-39c4-41cb-a9d1-402ad679a3e4)

### Environment

- Operating System:
- Browser (if applicable):
- Version:

**Comment by tg201005** [comment]
1. 아마, 페이지가 바뀌어 기존 패런트 노드가 없을 때, 에러가 발생하는 것으로 보임. 
2. 즉, 토너먼트 로그 컴포넌트가 업되기 전에, main 페이지로 이동하면 에러가 발생함. 
3. 이에 대한 예외 처리 진행할 예정.

**Comment by tg201005** [comment]
해결
